reload:
  name: Reload
  description: Reload localtuya and reconnect to all devices.

set_dp:
  name: Set datapoint
  description: Change the value of a datapoint (DP)
  fields:
    device_id:
      name: Device ID
      description: Device ID of device to change datapoint value for
      example: 11100118278aab4de001
    dp:
      name: Datapoint index
      description: Datapoint index
      example: 1
    value:
      name: New value
      description: New value to set
      example: False
